# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 844)
        MainWindow.setStyleSheet("/* Style For Info fram */\n"
"\n"
"#info_frame{\n"
"background-color:#fff;\n"
"border:none;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"/* style for label input and combo box */\n"
"#info_freme Qlabel,\n"
"#info_freme QLineEdit,\n"
"#info_freme QComboBox,\n"
"#function_frame QPushButton,\n"
"QHeaderView::section{\n"
"font-family:Segoe Ui Semibold;\n"
"font-size:12px;\n"
"}\n"
"\n"
"#function_frame QPushButton{\n"
"height:50px;\n"
"}\n"
"\n"
"#addBtn{\n"
"height:40px;\n"
"font-family:Segoe Ui Semibold;\n"
"font-size:14px;\n"
"padding:5px 10px;\n"
"border:2px solid #f0f0f0;\n"
"border-radius:5px;\n"
"background-color:#84e8f7;\n"
"}\n"
"#addBtn:hover {\n"
"border-color:#4c96f7;\n"
"font-size:15px;\n"
"}\n"
"\n"
"/* style for label input and combo box info frame */\n"
"\n"
"#info_frame QLineEdit,\n"
"#info_frame QComboBox {\n"
"padding:4px 5px;\n"
"border: 1px solid #838383;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"\n"
"/* Focus style for input and combo*/\n"
"#info_frame QLineEdit:focus,\n"
"#info_frame QComboBox:focus {\n"
"border-color:#0055ff;\n"
"}\n"
"\n"
"\n"
"/* style for combo box drop dwon*/\n"
"\n"
"QComboBox::drop-down {\n"
"background: transparent;\n"
"borer:none;\n"
"maargin-right: 5px;\n"
"}\n"
"\n"
"/* style for dpwn aarrow icon in combo box*/\n"
"\n"
"QComboBox::down-arrow {\n"
"image:url(/assets/images/arrow.svg);\n"
"}\n"
"\n"
"\n"
"/* style for the view_frame */\n"
"#view_frame {\n"
"background-color:#fff;\n"
"border:none;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"\n"
"\n"
"/* style for the border of QTabWidget */\n"
"\n"
"QTableWidget {\n"
"border-radius:3px;\n"
"border:1px solid #f0f0f0;\n"
"}\n"
"\n"
"/* style for the table header section */\n"
"\n"
"QHeaderView::section {\n"
"border:none;\n"
"border-bottom:1px solid #d0c6ff;\n"
"text-align:left;\n"
"padding:3px 5px;\n"
"\n"
"}\n"
"\n"
"/* style for the table items */\n"
"\n"
"QTableWidget::item {\n"
"border-bottom:1px solid #d0c6ff;\n"
"color:#000;\n"
"padding-left:3px;\n"
"}\n"
"\n"
"\n"
"/* style for the buttons in function_frame */\n"
"\n"
"#function_frame QPushButton {\n"
"font-size:14px;\n"
"padding:5px 10px;\n"
"border:2px solid #f0f0f0;\n"
"border-radius:5px;\n"
"background-color:#84e8f7;\n"
"}\n"
"\n"
"/* style for delete_btn*/\n"
"\n"
"#function_frame #deleteBtn {\n"
"background-color:#ff8183;\n"
"}\n"
"\n"
"/* hover style for buttons in function_frame*/\n"
"\n"
"#function_frame QPushButton:hover {\n"
"border-color:#4c96f7;\n"
"font-size:15px;\n"
"}\n"
"\n"
"/* hover style for deleteBtn */\n"
"\n"
"#function_frame #deleteBtn:hover {\n"
"border-color:#dc0004;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.info_frame = QtWidgets.QFrame(self.centralwidget)
        self.info_frame.setStyleSheet("")
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_3.setContentsMargins(30, 20, 30, 20)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.info_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.info_frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.info_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.info_frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.info_frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.info_frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.info_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.info_frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.info_frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.info_frame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.info_frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.info_frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.info_frame, 1, 0, 1, 2)
        self.view_frame = QtWidgets.QFrame(self.centralwidget)
        self.view_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view_frame.setObjectName("view_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.view_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.view_frame)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setStyleSheet("QTableWidget\n"
"{\n"
"color:red;\n"
"selection-color:green;\n"
"selection-background-color:blue;\n"
"}\n"
"\n"
"QTableWidget::item:selected \n"
"{\n"
"color:white;\n"
"background-color:blue;\n"
"}")
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.function_frame = QtWidgets.QFrame(self.view_frame)
        self.function_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.function_frame.setObjectName("function_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.function_frame)
        self.verticalLayout.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deleteBtn = QtWidgets.QPushButton(self.function_frame)
        self.deleteBtn.setMinimumSize(QtCore.QSize(200, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/images/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteBtn.setIcon(icon)
        self.deleteBtn.setObjectName("deleteBtn")
        self.verticalLayout.addWidget(self.deleteBtn)
        self.clearBtn = QtWidgets.QPushButton(self.function_frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/images/clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearBtn.setIcon(icon1)
        self.clearBtn.setObjectName("clearBtn")
        self.verticalLayout.addWidget(self.clearBtn)
        self.searchBtn = QtWidgets.QPushButton(self.function_frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/images/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchBtn.setIcon(icon2)
        self.searchBtn.setObjectName("searchBtn")
        self.verticalLayout.addWidget(self.searchBtn)
        self.selectBtn = QtWidgets.QPushButton(self.function_frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/images/select.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectBtn.setIcon(icon3)
        self.selectBtn.setObjectName("selectBtn")
        self.verticalLayout.addWidget(self.selectBtn)
        self.updateBtn = QtWidgets.QPushButton(self.function_frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/images/update.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateBtn.setIcon(icon4)
        self.updateBtn.setObjectName("updateBtn")
        self.verticalLayout.addWidget(self.updateBtn)
        self.gridLayout_4.addWidget(self.function_frame, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.view_frame, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 2)
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/images/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtn.setIcon(icon5)
        self.addBtn.setObjectName("addBtn")
        self.gridLayout_5.addWidget(self.addBtn, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Student id"))
        self.label_3.setText(_translate("MainWindow", "First name"))
        self.label_4.setText(_translate("MainWindow", "last name"))
        self.label_5.setText(_translate("MainWindow", "state"))
        self.comboBox.setItemText(0, _translate("MainWindow", "student"))
        self.comboBox.setItemText(1, _translate("MainWindow", "doctor"))
        self.comboBox.setItemText(2, _translate("MainWindow", "assestant"))
        self.comboBox.setItemText(3, _translate("MainWindow", "empoly"))
        self.comboBox.setItemText(4, _translate("MainWindow", "gard"))
        self.label_6.setText(_translate("MainWindow", "city"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "cairo"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "giza"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "aswan"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "elmansora"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Elmonofia"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "red sea"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "halwan"))
        self.label_7.setText(_translate("MainWindow", "Email Address"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "State"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "City"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Email Address"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "56565"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "aafad"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "asdfaf"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "asda"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "afa"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "adfadf"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.deleteBtn.setText(_translate("MainWindow", "Delete"))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.selectBtn.setText(_translate("MainWindow", "Select"))
        self.updateBtn.setText(_translate("MainWindow", "Update"))
        self.title_label.setText(_translate("MainWindow", "Students Information System"))
        self.addBtn.setText(_translate("MainWindow", "Add"))
